### PR TITLE
Update file ownership

### PR DESCRIPTION
**Pull request by edbeard**
Restrict merging approval credentials for source code and tests

### CODE REVIEW

**Review by WillTarran — APPROVED** [review]
Team has been added to collaborators list, so owners file valid ✅

**Review by WillTarran — CHANGES_REQUESTED** [review]
Hold up - on consideration, it's probably worth also including the poetry configs in this as well...

**Comment by edbeard** [comment]
@WillTarran I've now added the poetry configs and other files that should be protected to the CODEOWNERS

**Review by WillTarran — APPROVED** [review]
OK - LGTM!

**Pull request merged**
